# Replace "projectname" and "username"
image: golang:1.15

variables:
    BINARY_NAME: yamltojson
    GO_PROJECT: github.com/jdockerty/yaml-to-json-go

stages:
    - test
    - build
    - deploy

before_script:
    - mkdir -p ${GOPATH}/src/${GO_PROJECT}
    - mkdir -p ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}
    - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/${GO_PROJECT}/
    - cd ${GOPATH}/src/${GO_PROJECT}

test-yamltojson:
    stage: test
    script:
        - go mod download
        - go mod verify
        - go test -v -cover ./...

build-yamltojson:
    stage: build
    script:
        - go mod download
        - go build -o artifacts/${BINARY_NAME}
    artifacts:
        paths:
            - artifacts/${BINARY_NAME}


upload-artifact:
    stage: deploy
    image: python:latest
    script:
        - pip install awscli
        - aws s3 cp artifacts/${BINARY_NAME} s3://yaml-to-json-go