# Replace "projectname" and "username"
image: golang:1.15

variables:
    BIN_NAME: yamltojson
    ARTIFACTS_DIR: artifacts
    GO_PROJECT: github.com/jdockerty/yaml-to-json-go

stages:
    - test
    - build

before_script:
    - mkdir -p ${GOPATH}/src/${GO_PROJECT}
    - mkdir -p ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}
    - go mod download
    - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/${GO_PROJECT}/
    - cd ${GOPATH}/src/${GO_PROJECT}

test-yamltojson:
    stage: test
    script:
        - go mod verify
        - go test -v -cover ./...

build-yamltojson:
    stage: build
    script:
        - dep ensure
        - go build -o ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}/${BIN_NAME}
    artifacts:
    paths:
        - ${ARTIFACTS_DIR}

