# Replace "projectname" and "username"
image: golang:1.15

variables:
    BINARY_NAME: yamltojson
    ZIP_FILE: yamltojson.zip
    GO_PROJECT: github.com/jdockerty/yaml-to-json-go

stages:
    - test
    - build
    - deploy


test-yamltojson:
    stage: test
    script:
        - go mod download
        - go mod verify
        - go test -v -cover ./...

build-yamltojson:
    stage: build
    script:
        - go mod download
        - apt-get update -y 
        - apt-get install zip -y
        - make zip
        - mv ${ZIP_FILE} artifacts/
    artifacts:
        paths:
            - artifacts/${ZIP_FILE}
    only:
        - master


upload-artifact:
    stage: deploy
    image: python:latest
    script:
        - pip install awscli
        - aws s3 cp artifacts/${ZIP_FILE} s3://yaml-to-json-go
    only:
        - master